version: 0.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    build_crossguid

    build_opengex

    build_zlib

    build_bullet

    build_cef

    build_sdl

    build_glslangValidator

    build_spirvcross

    build

test_script:
- cmd: cmake --build build --target RUN_TESTS
