[package]
name = "engine-library"
version = "0.1.0"
authors = ["Chen Wenli <chenwenli@chenwenli.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.70"
winit = "0.22.2"
